### ISSUE TITLE
Add stateselectioncode and specialtyselectioncode constants

### ISSUE THREAD

**Issue by gauched** [tdar31/InquiryProgram#1]
It would be more clear to check against a constant value instead of using a number in all the checks for that state or specialty.

Example:

```
var michigan = 1;

if (stateSelectionCode === michigan) {
...
}
```

**Comment by tdar31** [comment]
This has been updated.  State selection codes are no longer numbers but variables which are named after each state they are representing.  The specialty selection codes are still numbers as they're only 4 total groups.  The grouping is purely based on which specialties fall into which price brackets and because some of the groups have over 30 specialties all grouped into one its hard to figure out how else they could be named.  All changes can be viewed in the lib/scriptmarginCalculation.js file
